<?php
$titles = array(
    array('label' => 'Use Case', 'href' => $this->url('dlcusecase', array())),
    array('label' => 'Type', 'href' => $this->url('dlcusecase/type', array())),
);

$actions = array(
    array('label' => 'Add new', 'icon' => 'plus', 'href' => $this->url('dlcusecase/type/add', array())),
);

// Render module page header
echo $this->partial('dlc-use-case/partials/header.phtml', array(
    'title'   => $titles,
    'image'   => '/img/no_thumbnail.png',
    'actions' => $actions
));

// Render searchbar
echo $this->partial('dlc-use-case/partials/searchbar.phtml', array(
    'route' => 'dlcusecase/type',
    'query' => $this->query,
    'actions' => $actions,
));


// Define properties for entity table
$displayProperties = array(
    '#'              => 'id',
    'Name'           => array(
        'orderBy'  => 'name',
        'property' => function($entity, $view) {
            $html = '<a href="' . $view->url('dlcusecase/type/show', array('id' => $entity->getId())) . '" title="Show ' . $view->escapeHtml($entity->getName()) . '">'
                  . $view->escapeHtml($entity->getName())
                  . '</a>';
            return $html;
        },
    ),
    'Use Cases'    => array(
        'orderBy'  => 'name',
        'property' => function($entity, $view) {
            return $entity->getUseCases()->count();
        },
    ),
    '<!--ACTIONS-->' => function($entity, $view) {
        $html = '<a href="' . $view->url('dlcusecase/type/show', array('id' => $entity->getId())) . '" title="Show ' . $view->escapeHtml($entity->getName()) . '">'
              .     '<i class="icon-eye-open"></i>'
              . '</a>'
              . '&nbsp;'
              . '<a href="' . $view->url('dlcusecase/type/edit', array('id' => $entity->getId())) . '" title="Edit ' . $view->escapeHtml($entity->getName()) . '">'
              .     '<i class="icon-pencil"></i>'
              . '</a>'
              . '&nbsp;'
              . '<a href="#deleteConfirmationModal_' . $entity->getId() . '" role="button" data-toggle="modal" title="Delete ' . $view->escapeHtml($entity->getName()) . '">'
              .     '<i class="icon-remove"></i>'
              . '</a>'
              . $view->partial('dlc-use-case/partials/deleteConfirmationModal.phtml', array(
                  'id'          => $entity->getId(),
                  'route'       => 'dlcusecase/type/delete',
                  'routeParams' => array('id' => $entity->getId()),
                  'question'    => 'Are you sure that you want to delete type "' . $view->escapeHtml($entity->getName()) . '"?',
              ));
        return $html;
    },
);

// Render entity table
echo $this->partial('dlc-use-case/partials/entityTable.phtml', array(
    'entities'          => $this->entities,
    'route'             => 'dlcusecase/type',
    'query'             => $this->query,
    'orderBy'           => $this->orderBy,
    'sort'              => $this->sort,
    'displayProperties' => $displayProperties,
));

// Render pagination controls
echo $this->paginationControl(
        $this->entities,
        'Sliding',
        'dlc-use-case/partials/pagination.phtml',
        array(
            'route' => 'dlcusecase/type',
            'query' => array(
                'query'   => $this->query,
                'orderBy' => $this->orderBy,
                'sort'    => $this->sort
            )
        )
);
?>