<?php
$formId = 'deleteConfirmationForm_' . $this->id;
$submitButtonId = 'deleteConfirmation_' . $this->id . '_SubmitButton';

if (!isset($this->form)) {
    $form = new \Zend\Form\Form($formId);

    $form->add(array(
        'type' => 'Zend\Form\Element\Hidden',
        'name' => 'id',
        'options' => array(
        ),
        'attributes' => array(
            'value'  => $this->id,
        ),
    ));

    $form->add(array(
        'type' => 'Zend\Form\Element\Hidden',
        'name' => 'confirmed',
        'options' => array(
        ),
        'attributes' => array(
            'value'  => 0,
        ),
    ));

    $form->add(new \Zend\Form\Element\Csrf('security'));
} else {
    $form = $this->form;
}

// Set attributes
$form->setAttribute('action', $this->url($this->route, $this->routeParams));
$form->setAttribute('method', 'post');
$form->setAttribute('id', $formId);

// Prepare the form elements
$form->prepare();
?>
<!-- Modal -->
<div id="deleteConfirmationModal_<?php echo $this->id ?>" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="deleteConfirmationModal_<?php echo $this->id ?>_Label" aria-hidden="true" style="text-align:left;">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="deleteConfirmationModal_<?php echo $this->id ?>_Label">Confirm delete</h3>
    </div>
    <div class="modal-body">
        <p><?php echo $this->escapeHtml($this->question) ?></p>
        <?php echo $this->form()->render($form) ?>
    </div>
    <div class="modal-footer">
        <button class="btn" data-dismiss="modal" aria-hidden="true">Cancel</button>
        <button class="btn btn-primary" id="<?php echo $submitButtonId ?>">Delete</button>
        <?php $this->inlineScript()->captureStart() ?>
            $(document).ready(function() {
                $('#<?php echo $submitButtonId ?>').click(function() {
                    $('#<?php echo $formId?> input[name="confirmed"]:input').val(1);

                    $('#<?php echo $formId?>').submit();
                });
            });
        <?php $this->inlineScript()->captureEnd() ?>
    </div>
</div>