<?php
    $form = $this->form;

    /*if (isset($this->query)) {
        $queryString = '?query=' . $this->query;
    } else {
        $queryString = '';
    }*/

    // Set attributes
    $form->setAttribute('action', $this->url($this->route, array('page' => 1), array('query' => $this->query)));
    $form->setAttribute('method', 'post');

    $form->setAttribute('class', 'form-horizontal');
    // Prepare the form elements
    $form->prepare();

    $messages = $form->getMessages();
?>
<ul class="nav">
    <li class="divider-vertical"></li>
    <li>
        <!-- Button to trigger modal -->
        <a href="#myModal" role="button" data-toggle="modal"><i class="icon-filter"></i>Filter</a>
    </li>
</ul>
<!-- Modal -->
<div id="myModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <?php
      // Render the opening tag
      echo $this->form()->openTag($form);
  ?>
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">Modal header</h3>
  </div>
  <div class="modal-body">
    <?php
    //Render form elements
    echo $this->partial('dlc-use-case/partials/formElements.phtml', array(
        'elements'   => $form->getElements(),
        'renderButtons' => false,
    ));
    ?>
  </div>
  <div class="modal-footer">
    <?php
    //Render form buttons
    echo $this->partial('dlc-use-case/partials/formElements.phtml', array(
        'elements'          => $form->getElements(),
        'renderButtonsOnly' => true,
    ));
    ?>
  </div>
  <?php
  // Render the closing tag
  echo $this->form()->closeTag();
  ?>
</div>