<?php
use ZendTest\Server\Reflection\function1;

$titles = array(
    array('label' => 'Use Case', 'href' => $this->url('dlcusecase', array())),
);

$actions = array(
    array('label' => 'Add new', 'icon' => 'plus', 'href' => $this->url('dlcusecase/add', array())),
    array('label' => 'Show diagramm', 'icon' => 'picture', 'href' => $this->url('dlcusecase/diagramm', array())),
);

// Render module page header
echo $this->partial('dlc-use-case/partials/header.phtml', array(
    'title'   => $titles,
    'image'   => '/img/no_thumbnail.png',
    'actions' => $actions
));

// Render searchbar
echo $this->partial('dlc-use-case/partials/searchbar.phtml', array(
    'route' => 'dlcusecase',
    'query' => $this->query,
    'actions' => $actions,
));


// Define properties for entity table
$displayProperties = array(
    '#'              => 'id',
    'Name'           => 'name',
    'Category' => function($entity, $view) {
        return $entity->getCategory()->getTitle();
    },
    'Priority' => function($entity, $view) {
        return $entity->getPriority()->getName();
    },
    'Type' => function($entity, $view) {
        return $entity->getType()->getName();
    },
    'Name'           => 'name',
    'Dependencies' => function($entity, $view) {
        return $entity->getDependencies()->count();
    },
    '<!--ACTIONS-->' => function($entity, $view) {
        $html = '<a href="' . $view->url('dlcusecase/show', array('id' => $entity->getId())) . '" title="Show ' . $view->escapeHtml($entity->getName()) . '">'
              .     '<i class="icon-eye-open"></i>'
              . '</a>'
              . '&nbsp;'
              . '<a href="' . $view->url('dlcusecase/edit', array('id' => $entity->getId())) . '" title="Edit ' . $view->escapeHtml($entity->getName()) . '">'
              .     '<i class="icon-pencil"></i>'
              . '</a>'
              . '&nbsp;';

        $wikiPage = $this->dlcRenderWikiTemplate()->render($entity);

        if ($wikiPage) {
            $html .= '<a href="#wikiPageModal_' . $entity->getId() . '" role="button" data-toggle="modal" title="Show generated wiki page for ' . $view->escapeHtml($entity->getName()) . '">'
                   .     '<i class="icon-file"></i>'
                   . '</a>'. '&nbsp;';

            $wikiPageModal = '<div id="wikiPageModal_' . $entity->getId() . '" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="wikiPageModal_' . $entity->getId() . 'Label" aria-hidden="true">'
                           .     '<div class="modal-header">'
                           .         '<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>'
                           .         '<h3 id="wikiPageModal_' . $entity->getId() . 'Label">Generated wiki page</h3>'
                           .     '</div>'
                           .     '<div class="modal-body">'
                           .         '<p><pre>' . $wikiPage. '</pre></p>'
                           .     '</div>'
                           .     '<div class="modal-footer">'
                           .         '<button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>'
                           .     '</div>'
                           . '</div>';

        } else {
            $wikiPageModal = '';
        }

        $html .= '<a href="#deleteConfirmationModal_' . $entity->getId() . '" role="button" data-toggle="modal" title="Delete ' . $view->escapeHtml($entity->getName()) . '">'
               .     '<i class="icon-remove"></i>'
               . '</a>'
               . $wikiPageModal
               . $view->partial('dlc-use-case/partials/deleteConfirmationModal.phtml', array(
                   'id'          => $entity->getId(),
                   'route'       => 'dlcusecase/delete',
                   'routeParams' => array('id' => $entity->getId()),
                   'question'    => 'Are you sure that you want to delete priority "' . $view->escapeHtml($entity->getName()) . '"?',
               ));

        return $html;
    },
);

// Render entity table
echo $this->partial('dlc-use-case/partials/entityTable.phtml', array(
    'entities'          => $this->entities,
    'route'             => 'dlcusecase',
    'query'             => $this->query,
    'orderBy'           => $this->orderBy,
    'sort'              => $this->sort,
    'displayProperties' => $displayProperties,
));

// Render pagination controls
echo $this->paginationControl(
        $this->entities,
        'Sliding',
        'dlc-use-case/partials/pagination.phtml',
        array(
            'route' => 'dlcusecase/list',
            'query' => array(
                'query'   => $this->query,
                'orderBy' => $this->orderBy,
                'sort'    => $this->sort
            )
        )
);
?>