<?php 
$titles = array(
    array('label' => 'Use Case', 'href' => $this->url('dlcusecase', array())),
    array('label' => 'Show', 'href' => $this->url('dlcusecase/show', array('id' => $this->entity->getId()))),
);

$actions = array(
    array('label' => 'Edit', 'icon' => 'pencil', 'href' => $this->url('dlcusecase/edit', array('id' => $this->entity->getId()))),
);

echo $this->partial('dlc-use-case/partials/header.phtml', array(
    'title'   => $titles,
    'image'   => '/img/no_thumbnail.png',
    'actions' => $actions
));
?>
<div class="row-fluid">
    <div class="span12">
        <div class="btn-group">
            <a class="btn" href="<?php echo $this->url('dlcusecase', array()) ?>" title="Back to list"><i class="icon-list"></i> Back to list</a>
            <a class="btn" href="<?php echo $this->url('dlcusecase/edit', array('id' => $this->entity->getId())) ?>" title="edit"><i class="icon-pencil"></i> Edit</a>
            <a class="btn" href="#deleteConfirmationModal_<?php echo $this->entity->getId() ?>" role="button" data-toggle="modal" title="delete"><i class="icon-trash"></i> Delete</a>
        </div>
        <?php echo $this->partial('dlc-use-case/partials/deleteConfirmationModal.phtml', array(
            'id'          => $this->entity->getId(),
            'route'       => 'dlcusecase/delete',
            'routeParams' => array('id' => $this->entity->getId()),
            'question'    => 'Are you sure that you want to delete "' . $this->escapeHtml($this->entity->getName()) . '"?',
        ));?>
    </div>
</div>

<div class="row-fluid">
    <div class="span12">
        <dl>
            <dt><?php echo $this->translate('ID') ?></dt>
            <dd><pre><?php echo $this->entity->getId() ?></pre></dd>
            
            <dt><?php echo $this->translate('Name') ?></dt>
            <dd><pre><?php echo $this->entity->getName() ?></pre></dd>
            
            <dt><?php echo $this->translate('Type') ?></dt>
            <dd><pre><?php echo $this->entity->getType()->getName() ?></pre></dd>
            
            <dt><?php echo $this->translate('Category') ?></dt>
            <dd><pre><?php echo $this->entity->getCategory()->getTitle() ?></pre></dd>
            
            <dt><?php echo $this->translate('Priority') ?></dt>
            <dd><pre><?php echo $this->entity->getPriority()->getName() ?></pre></dd>
            
            <dt><?php echo $this->translate('Link') ?></dt>
            <dd><pre><?php echo $this->entity->getLink() ?></pre></dd>
            
            <dt><?php echo $this->translate('Used by dependencies') ?></dt>
            <dd><pre><?php foreach ($this->entity->getUsedByDependencies() as $dependency): ?>* (<?php echo $dependency->getType() ?>) <?php echo $dependency->getFromNode()->getExtendedName() . PHP_EOL ?>
<?php endforeach; ?></pre>
            </dd>
            
            <dt><?php echo $this->translate('Dependencies to') ?></dt>
            <dd>
                <pre><?php foreach ($this->entity->getDependencies() as $dependency): ?>* (<?php echo $dependency->getType() ?>) <?php echo $dependency->getToNode()->getExtendedName() . PHP_EOL ?>
<?php endforeach; ?></pre></dd>
        </dl>
    </div>
</div>