<?php
$titles = array(
    array('label' => 'Use Case', 'href' => $this->url('dlcusecase', array())),
    array('label' => 'Show', 'href' => $this->url('dlcusecase/show', array('id' => $this->entity->getId()))),
);

$actions = array(
    array('label' => 'Edit', 'icon' => 'pencil', 'href' => $this->url('dlcusecase/edit', array('id' => $this->entity->getId()))),
);

echo $this->partial('dlc-use-case/partials/header.phtml', array(
    'title'   => $titles,
    'image'   => '/img/no_thumbnail.png',
    'actions' => $actions
));
?>
<?php $this->placeholder('useCaseData')->captureStart(); ?>
<div class="row-fluid">
    <div class="span12">
        <div class="btn-group">
            <a class="btn" href="<?php echo $this->url('dlcusecase', array()) ?>" title="Back to list"><i class="icon-list"></i> Back to list</a>
            <a class="btn" href="<?php echo $this->url('dlcusecase/edit', array('id' => $this->entity->getId())) ?>" title="edit"><i class="icon-pencil"></i> Edit</a>
            <a class="btn" href="#deleteConfirmationModal_<?php echo $this->entity->getId() ?>" role="button" data-toggle="modal" title="delete"><i class="icon-trash"></i> Delete</a>
        </div>
        <?php echo $this->partial('dlc-use-case/partials/deleteConfirmationModal.phtml', array(
            'id'          => $this->entity->getId(),
            'route'       => 'dlcusecase/delete',
            'routeParams' => array('id' => $this->entity->getId()),
            'question'    => 'Are you sure that you want to delete "' . $this->escapeHtml($this->entity->getName()) . '"?',
        ));?>
    </div>
</div>

<div class="row-fluid">
    <div class="span12">
        <dl>
            <dt><?php echo $this->translate('ID') ?></dt>
            <dd><pre><?php echo $this->escapeHtml($this->entity->getId()) ?></pre></dd>

            <dt><?php echo $this->translate('Name') ?></dt>
            <dd><pre><?php echo $this->escapeHtml($this->entity->getName()) ?></pre></dd>

            <dt><?php echo $this->translate('Type') ?></dt>
            <dd><pre><?php echo $this->escapeHtml($this->entity->getType()->getName()) ?></pre></dd>

            <?php // Display optional properties ?>
            <?php foreach ($this->options->getOptionalFields() as $fieldName => $fieldLabel): ?>
                <?php
                    $value = $this->entity->$fieldName;

                    if (is_object($value)) {
                        if (method_exists($value, 'getTitle')) {
                            $value = $value->getTitle();
                        } elseif (method_exists($value, 'getName')) {
                            $value = $value->getName();
                        } else {
                            throw new \RuntimeException('Cannot load value for object');
                        }
                    }
                ?>
                <?php if ($fieldName == 'link'): ?>
                    <dt><?php echo $this->translate($fieldLabel) ?></dt>
                    <dd><pre><a href="<?php echo $this->entity->getLink() ?>" target="_blank"><?php echo $this->entity->getLink() ?></a></pre></dd>
                <?php else: ?>
                    <dt><?php echo $this->translate($fieldLabel) ?></dt>
                    <dd><pre><?php echo $this->escapeHtml($value) ?></pre></dd>
                <?php endif; ?>
            <?php endforeach; ?>

            <?php
            if ($this->entity->getUsedByDependencies()->count() < 1) {
                $depBySpace = '&nbsp;';
            } else {
                $depBySpace = '';
            }
            if ($this->entity->getDependencies()->count() < 1) {
                $depSpace = '&nbsp;';
            } else {
                $depSpace = '';
            }
            ?>

            <dt><?php echo $this->translate('Used by dependencies') ?></dt>
            <dd><pre><?php echo $depBySpace ?><?php foreach ($this->entity->getUsedByDependencies() as $dependency): ?>- (<?php echo $dependency->getType() ?>) <?php echo $dependency->getFromNode()->getExtendedName() . PHP_EOL ?>
<?php endforeach; ?> </pre>
            </dd>

            <dt><?php echo $this->translate('Dependencies to') ?></dt>
            <dd><pre><?php echo $depSpace ?><?php foreach ($this->entity->getDependencies() as $dependency): ?>* (<?php echo $dependency->getType() ?>) <?php echo $dependency->getToNode()->getExtendedName() . PHP_EOL ?>
<?php endforeach; ?></pre></dd>
        </dl>
    </div>
</div>
<?php $this->placeholder('useCaseData')->captureEnd() ?>

<?php if ($this->options->getDisplayDiagrammInDetailView() && isset($this->diagramm)) {
    $wikiPage = $this->dlcRenderWikiTemplate()->render($this->entity);
    if ($wikiPage) {
        $infoTab = array(
            'label' => 'Generated wiki page',
            'data'  => '<pre>' . $wikiPage . '</pre>',
        );
    } else {
        $infoTab = null;
    }

    echo $this->partial('dlc-diagramm/partials/diagrammInTabs.phtml', array(
        'diagramm'  => $this->diagramm,
        'displayAs' => $this->options->getDisplayDiagrammAs(),
        'dataTab'   => array(
            'label' => 'Use case data',
            'data'  => $this->placeholder('useCaseData'),
        ),
        'infoTab'   => $infoTab
    ));
} else {
    echo $this->placeholder('useCaseData');
} ?>